version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./Docker:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root